package com.danilovfa.uikit.theme.colors

// TODO Make material theme later
//internal val materialLightColorScheme: ColorScheme = ColorScheme(
//    primary = appColorLightPalette.buttonPrimary,
//    onPrimary = appColorLightPalette.buttonOnPrimary,
//    primaryContainer = primaryContainer,
//    onPrimaryContainer = onPrimaryContainer,
//    inversePrimary = inversePrimary,
//    secondary = secondary,
//    onSecondary = onSecondary,
//    secondaryContainer = secondaryContainer,
//    onSecondaryContainer = onSecondaryContainer,
//    tertiary = appColorLightPalette.textTertiary,
//    onTertiary = appColorLightPalette.,
//    tertiaryContainer = tertiaryContainer,
//    onTertiaryContainer = onTertiaryContainer,
//    background = background,
//    onBackground = onBackground,
//    surface = surface,
//    onSurface = onSurface,
//    surfaceVariant = surfaceVariant,
//    onSurfaceVariant = onSurfaceVariant,
//    surfaceTint = surfaceTint,
//    inverseSurface = inverseSurface,
//    inverseOnSurface = inverseOnSurface,
//    error = appColorLightPalette.error,
//    onError = appColorLightPalette.onError,
//    errorContainer = errorContainer,
//    onErrorContainer = onErrorContainer,
//    outline = outline,
//    outlineVariant = outlineVariant,
//    scrim = appColorLightPalette.textSecondary,
//    surfaceBright = Color.Unspecified,
//    surfaceDim = Color.Unspecified,
//    surfaceContainer = Color.Unspecified,
//    surfaceContainerHigh = Color.Unspecified,
//    surfaceContainerHighest = Color.Unspecified,
//    surfaceContainerLow = Color.Unspecified,
//    surfaceContainerLowest = Color.Unspecified,
//)